BBBBBBB BBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
    XXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB