BBBBBBB BBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
    XXX XXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXXXX XXX XXXX XX XXX XXXX XX XXX XXX XXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX
    XXXXXXX
BBBBBBBB