# Generated by Django 4.1.6 on 2023-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_comment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='products/cover'),
        ),
    ]
